plugins/Personas/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::plugin(
    'Personas',
    ['path' => '/personas'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

plugins/Personas/src/Model/Entity/Persona.php
<?php
namespace Personas\Model\Entity;

use Cake\ORM\Entity;

class Persona extends Entity{
    
    protected $_accessible = [
        'cedula' => true,
        'prefijo' => true,
        'primer_nombre' => true,
        'segundo_nombre' => true,
        'primer_apellido' => true,
        'segundo_apellido' => true,
        'genero_id' => true,
        'telefono1' => true,
        'telefono2' => true,
        'correo_electronico' => true,
        'status_id' => true,
        'created' => true,
        'modified' => true,
        'descripcion' => true
    ];

    protected $_virtual = ['nombre_apellido'];

    protected function _getNombreApellido() {
        if(isset($this->_properties['primer_nombre']) && isset($this->_properties['primer_apellido'])){
            return $this->_properties['primer_nombre'] . ' ' . $this->_properties['primer_apellido'];
        }
        return "";
    }
}

plugins/Personas/src/Model/Table/PersonasTable.php
<?php
namespace Personas\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class PersonasTable extends Table{
    
    public function initialize(array $config){
        parent::initialize($config);

        $this->setTable('personas');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Generos', [
            'foreignKey' => 'genero_id',
            'joinType' => 'INNER',
            'className' => 'Descripcions'
        ]);
        $this->belongsTo('Status', [
            'foreignKey' => 'status_id',
            'joinType' => 'INNER',
            'className' => 'Descripcions'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('cedula')
            ->maxLength('cedula', 20)
            ->requirePresence('cedula', 'create')
            ->notEmptyString('cedula','Ingrese cédula.')
            ->add('cedula', 'unique', ['rule' => 'validateUnique', 'provider' => 'table','message'=>'Cédula registrada previamente']);

        $validator
            ->scalar('prefijo')
            ->maxLength('prefijo', 5)
            ->requirePresence('prefijo', 'create')
            ->notEmptyString('prefijo');

        $validator
            ->scalar('primer_nombre')
            ->maxLength('primer_nombre', 100)
            ->requirePresence('primer_nombre', 'create')
            ->notEmptyString('primer_nombre','Ingrese primer nombre.');

        $validator
            ->scalar('segundo_nombre')
            ->maxLength('segundo_nombre', 100)
            ->allowEmptyString('segundo_nombre');

        $validator
            ->scalar('primer_apellido')
            ->maxLength('primer_apellido', 100)
            ->requirePresence('primer_apellido', 'create')
            ->notEmptyString('primer_apellido','Ingrese primer apellido.');

        $validator
            ->scalar('segundo_apellido')
            ->maxLength('segundo_apellido', 100)
            ->allowEmptyString('segundo_apellido');

        $validator
            ->scalar('genero_id')
            ->requirePresence('genero_id', 'create')
            ->notEmpty('genero_id','Seleccione género.');

        $validator
            ->scalar('telefono1')
            ->maxLength('telefono1', 100)
            ->requirePresence('telefono1', 'create')
            ->notEmptyString('telefono1','Ingrese teléfono 1');

        $validator
            ->scalar('telefono2')
            ->maxLength('telefono2', 100)
            ->allowEmptyString('telefono2');

        $validator
            ->scalar('correo_electronico')
            ->maxLength('correo_electronico', 300)
            ->requirePresence('correo_electronico', 'create')
            ->notEmptyString('correo_electronico','Ingrese correo electrónico');

        return $validator;
    }

    
    public function buildRules(RulesChecker $rules){
        $rules->add($rules->isUnique(['cedula']));
        $rules->add($rules->existsIn(['genero_id'], 'Generos'));
        $rules->add($rules->existsIn(['status_id'], 'Status'));

        return $rules;
    }


    public function eliminarPersona($id){
        $persona=$this->get($id);
        $persona->status_id=102;
        return $this->save($persona) ? true : false;
    }


    public function reciclarPersona($id){
        $persona=$this->get($id);
        $persona->status_id=101;
        return $this->save($persona) ? true : false;
    }

    public function validarPersonaIdentificacion($prefijo,$cedula){
        $consulta=$this->find()->where(['prefijo'=>$prefijo,'cedula'=>$cedula])->all();
        return $consulta->toArray();
    }

}

plugins/Personas/src/Controller/PersonasController.php
<?php
namespace Personas\Controller;

use Personas\Controller\AppController;

class PersonasController extends AppController{

    public function listar(){
        if(isset($this->request['data']['filtros']) || isset($this->request->query['sort'])){
            $this->paginate = [
                'contain' => ['Status', 'Generos'],
                'sortWhitelist' => ['id','cedula','primer_nombre','primer_apellido','Generos.nombre'],
                'limit' => 10
            ];

            if(!empty($this->request->data['filtros']['prefijo'])){
                $this->paginate['conditions'][] = [ 
                    'AND' => ['Personas.prefijo' => $this->request->data['filtros']['prefijo']]];
            }

            if(!empty($this->request->data['filtros']['cedula'])){
                $this->paginate['conditions'][] = [ 
                    'AND' => ['Personas.cedula' => $this->request->data['filtros']['cedula']]];
            }

            if(!empty($this->request->data['filtros']['primer_nombre'])){
                $this->paginate['conditions'][] = [ 
                    'AND' => ['LOWER(Personas.primer_nombre) LIKE' =>  '%'.strtolower($this->request->data['filtros']['primer_nombre']).'%']];
            }

            if(!empty($this->request->data['filtros']['primer_apellido'])){
                $this->paginate['conditions'][] = [ 
                    'AND' => ['LOWER(Personas.primer_apellido) LIKE' =>  '%'.strtolower($this->request->data['filtros']['primer_apellido']).'%']];
            }

            if(!empty($this->request->data['filtros']['genero_id'])){
                $this->paginate['conditions'][] = [ 
                    'AND' => ['Personas.genero_id' => $this->request->data['filtros']['genero_id']]];
            }

            if(!empty($this->request->data['filtros']['mostrar'])){
                $this->paginate['conditions'][] = [ 
                    'AND' => ['Personas.status_id' => $this->request->data['filtros']['mostrar']]];
            }
            $personas = $this->paginate($this->Personas);

            $this->set(compact('personas'));
            $this->render("listar_personas");
        }

        if(!isset($this->request['data']['filtros'])){
            $personas = $this->Personas;
            $generosList = $this->Personas->Generos->find('list', ['limit' => 200])->where(['padre_id'=>'10']);
            $prefijosList = $this->listarPrefijosPersonas();
            $this->set(compact('personas','generosList','prefijosList'));
        }
    }

    
    public function consultar($id = null){
        $persona = $this->Personas->get($id, [
            'contain' => ['Generos','Status']
        ]);

        $this->set('persona', $persona);
    }


    public function registrar(){
        $persona = $this->Personas->newEntity();

        if (isset($this->request['data']['filtros'])){
            $persona->status_id=101; //Activo por defecto

            $generosList = $this->Personas->Generos->find('list', ['limit' => 200])->where(['padre_id'=>'10']);
            $prefijosList = $this->listarPrefijosPersonas();
            $this->set(compact('persona','generosList','prefijosList'));
        }

        if (!isset($this->request['data']['filtros'])){
            if ($this->request->is('post')) {
                $persona = $this->Personas->patchEntity($persona, $this->request->getData());
                if(count($persona->errors()) > 0){ //Validación a través del modelo...
                    $errores=$this->formatearErrores($persona->errors());
                    echo json_encode(['result'=>false, 'errors' => $errores]);
                    exit();
                }
                if ($this->Personas->save($persona)){
                    echo json_encode(['result'=>true, 'mensaje'=>'Persona registrada exitosamente']);
                }else{
                    echo json_encode(['result'=>false, 'mensaje'=>'Error registrando persona']);
                }
            }else{
                echo json_encode(['result'=>false, 'mensaje'=>'Error registrando persona']);
            }
            exit();
        }
    }

    public function editar($id = null){
        $persona = $this->Personas->get($id,['contain' => ['Status','Generos']]);

        if (isset($this->request['data']['filtros'])){
            $generosList = $this->Personas->Generos->find('list', ['limit' => 200])->where(['padre_id'=>'10']);
            $prefijosList = $this->listarPrefijosPersonas();
            $this->set(compact('persona','generosList','prefijosList'));
        }

        if (!isset($this->request['data']['filtros'])){
            $persona = $this->Personas->get($id);
            if ($this->request->is('put')){
                $persona = $this->Personas->patchEntity($persona, $this->request->getData());
                if(count($persona->errors()) > 0){ //Validación a través del modelo...
                    $errores=$this->formatearErrores($persona->errors());
                    echo json_encode(['result'=>false, 'errors' => $errores]);
                    exit();
                }
                if ($this->Personas->save($persona)){
                    echo json_encode(['result'=>true, 'mensaje'=>'Persona editada exitosamente']);
                }else{
                    echo json_encode(['result'=>false, 'mensaje'=>'Error editando persona']);
                }
            }else{
                echo json_encode(['result'=>false, 'mensaje'=>'Error editando persona']);
            }
            exit();
        }

    }


    public function eliminar($id){
        $eliminar=$this->Personas->eliminarPersona($id);
        if($eliminar){
            echo json_encode(['result'=>true, 'mensaje'=>'Persona eliminada con éxito']);
        }else{
            echo json_encode(['result'=>false, 'mensaje'=>'Ha ocurrido un error, por favor intente nuevamente']);
        }
        $this->autoRender = false;
    }


    public function reciclar($id){
        $reciclar=$this->Personas->reciclarPersona($id);
        if($reciclar){
            echo json_encode(['result'=>true, 'mensaje'=>'Persona reciclada con éxito']);
        }else{
            echo json_encode(['result'=>false, 'mensaje'=>'Ha ocurrido un error, por favor intente nuevamente']);
        }
        $this->autoRender = false;
    }
    
}

plugins/Personas/src/Template/Personas/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $persona
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Personas'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Descripcions'), ['controller' => 'Descripcions', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Descripcion'), ['controller' => 'Descripcions', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="personas form large-9 medium-8 columns content">
    <?= $this->Form->create($persona) ?>
    <fieldset>
        <legend><?= __('Add Persona') ?></legend>
        <?php
            echo $this->Form->control('cedula');
            echo $this->Form->control('prefijo');
            echo $this->Form->control('primer_nombre');
            echo $this->Form->control('segundo_nombre');
            echo $this->Form->control('primer_apellido');
            echo $this->Form->control('segundo_apellido');
            echo $this->Form->control('genero_id');
            echo $this->Form->control('telefono1');
            echo $this->Form->control('telefono2');
            echo $this->Form->control('correo_electronico');
            echo $this->Form->control('status_id', ['options' => $descripcions]);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

plugins/Personas/src/Template/Personas/consultar.ctp
<div class="modal fade" id="modal-consultar-persona" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="largeModalLabel">Consultar persona</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-bordered">
                            <tr class="table-active">
                                <th>Cedula</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                            </tr>

                            <tr>
                                <td><?= strtoupper($persona->prefijo)."-".$persona->cedula; ?></td>
                                <td><?= $persona->primer_nombre." ".$persona->segundo_nombre; ?></td>
                                <td><?= $persona->primer_apellido." ".$persona->segundo_apellido; ?></td>
                            </tr>

                            <tr>
                                <th>Género</th>
                                <th>Teléfono 1</th>
                                <th>Teléfono 2</th>
                            </tr>

                            <tr>
                                <td><?= $persona->genero->nombre; ?></td>
                                <td><?= $persona->telefono1; ?></td>
                                <td><?= $persona->telefono2; ?></td>
                            </tr>

                            <tr>
                                <th>Correo electrónico</th>
                                <th colspan="2">Eliminado</th>
                            </tr>

                            <tr>
                                <td><?= $persona->correo_electronico; ?></td>
                                <td colspan="2">
                                    <?php
                                    $clase=$persona->status_id == 101 ? 'badge badge-success' : 'badge badge-danger';
                                    ?>
                                    <h4><span class="<?= $clase ?>"><?= $persona->status_id == 101 ? 'No' : 'Si'; ?></span></h4>
                                </td>
                            </tr>

                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("document").ready(function(){
        $("#modal-consultar-persona").modal('show');
    });
</script>

plugins/Personas/src/Template/Personas/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $persona
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $persona->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $persona->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Personas'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Descripcions'), ['controller' => 'Descripcions', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Descripcion'), ['controller' => 'Descripcions', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="personas form large-9 medium-8 columns content">
    <?= $this->Form->create($persona) ?>
    <fieldset>
        <legend><?= __('Edit Persona') ?></legend>
        <?php
            echo $this->Form->control('cedula');
            echo $this->Form->control('prefijo');
            echo $this->Form->control('primer_nombre');
            echo $this->Form->control('segundo_nombre');
            echo $this->Form->control('primer_apellido');
            echo $this->Form->control('segundo_apellido');
            echo $this->Form->control('genero_id');
            echo $this->Form->control('telefono1');
            echo $this->Form->control('telefono2');
            echo $this->Form->control('correo_electronico');
            echo $this->Form->control('status_id', ['options' => $descripcions]);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

plugins/Personas/src/Template/Personas/listar_personas.ctp
<div class="table-responsive table-responsive-data2">
    <table class="table table-data2 table-hover">
        <thead>
            <tr>
                <th scope="col" class="sorter"><?= $this->Paginator->sort('id') ?></th>
                <th scope="col" class="sorter"><?= $this->Paginator->sort('cedula') ?></th>
                <th scope="col" class="sorter"><?= $this->Paginator->sort('primer_nombre') ?></th>
                <th scope="col" class="sorter"><?= $this->Paginator->sort('primer_apellido') ?></th>
                <th scope="col" class="sorter"><?= $this->Paginator->sort('Generos.nombre','Género') ?></th>
                <th scope="col" class="sorter">Eliminado</th>
                <th scope="col" class="actions encabezado-fijo"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($personas as $persona): ?>
            <tr>
                <td><?= $this->Number->format($persona->id); ?></td>
                <td style="white-space: nowrap;"><?= strtoupper($persona->prefijo)."-".$persona->cedula; ?></td>
                <td><?= $persona->primer_nombre; ?></td>
                <td><?= $persona->primer_apellido; ?></td>
                <td><?= $persona->genero->nombre ?></td>
                <td>
                    <?php
                    $clase=$persona->status_id == 101 ? 'badge badge-success' : 'badge badge-danger';
                    ?>
                    <h4><span class="<?= $clase ?>"><?= $persona->status_id == 101 ? 'No' : 'Si'; ?></span></h4>
                </td>
                <td class="actions columna-fija" style="white-space: nowrap;">
                    <?php if($persona->status_id == 101){ ?>
                        <button type="button" class="btn btn-info btn-sm btn-consultar" data-url="<?= $this->Url->build(["action" => "consultar", $persona->id]); ?>" data-toggle="tooltip" data-placement="bottom" title="Consultar" data-original-title="Consultar"><i class="fa fa-eye"></i></button>
                        <button type="button" class="btn btn-primary btn-sm btn-editar" data-url="<?= $this->Url->build(["action" => "editar", $persona->id]); ?>" data-toggle="tooltip" data-placement="bottom" title="Editar" data-original-title="Editar"><i class="fa fa-edit"></i></button>
                    <?php } ?>

                    <?php if($persona->status_id == 101){ ?>
                        <button type="button" class="btn btn-danger btn-sm btn-eliminar" data-toggle="tooltip" data-placement="bottom" title="Eliminar" data-original-title="Eliminar" data-url="<?= $this->Url->build(["action" => "eliminar", $persona->id]); ?>"><i class="fa fa-trash"></i></button>
                    <?php } ?>

                    <?php if($persona->status_id == 102){ ?>
                        <button type="button" class="btn btn-success btn-sm btn-reciclar" data-toggle="tooltip" data-placement="bottom" title="Reciclar" data-original-title="Reciclar" data-url="<?= $this->Url->build(["action" => "reciclar", $persona->id]); ?>"><i class="fa fa-recycle"></i></button>
                    <?php } ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="paginator">
    <ul class="pagination">
        <?= $this->Paginator->first('<< ' . __('first')) ?>
        <?= $this->Paginator->prev('< ' . __('previous')) ?>
        <?= $this->Paginator->numbers() ?>
        <?= $this->Paginator->next(__('next') . ' >') ?>
        <?= $this->Paginator->last(__('last') . ' >>') ?>
    </ul>
    <p><?= $this->Paginator->counter(['format' => __('Página <b>{{page}}</b> de <b>{{pages}}</b>, mostrando <b>{{current}}</b> registros de <b>{{count}}</b> en total')]) ?></p>
</div>

<script type="text/javascript">
    $(".sorter a, .pagination a").click(function() {
        if (!$(this).attr('href')){
            return false;
        }

        href=$(this).attr('href');
        
        $.ajax({
            type: "POST",
            url: href,
            dataType: "html",
            data:$("#listado-personas").serialize(),
            beforeSend: function(xhr){
                xhr.setRequestHeader('X-CSRF-Token', $('[name="_csrfToken"]').val());
                $(".page-loader").removeClass('hide');
            },
            success: function(data){
                $("#container-listado").html(data);
                $(".page-loader").addClass('hide');
            },
            error: function (status, error, datos){
               $(".page-loader").addClass('hide');
               Swal.fire({icon: 'error',title: '',text: 'Ha ocurrido un error, por favor intente nuevamente',footer: ''});
            }
        });

        return false;
    });


    $(".btn-consultar").click(function(){
        url=$(this).data('url');
        data=$("#listado-personas").serialize();
        $.ajax({
            type: "POST",
            url: url,
            dataType: "html",
            data:data,
            beforeSend: function(xhr){
                xhr.setRequestHeader('X-CSRF-Token', $('[name="_csrfToken"]').val());
                $(".page-loader").removeClass('hide');
            },
            success: function(data){
                $("#modal-container").html(data);
                $(".page-loader").addClass('hide');
            },
            error: function (status, error, datos){
                $(".page-loader").addClass('hide');
                Swal.fire({icon: 'error',title: '',text: 'Ha ocurrido un error, por favor intente nuevamente',footer: ''});
            }
        });
    });


    $(".btn-editar").click(function(){
        url=$(this).data('url');
        data=$("#listado-personas").serialize();
        $.ajax({
            type: "POST",
            url: url,
            dataType: "html",
            data:data,
            beforeSend: function(xhr){
                xhr.setRequestHeader('X-CSRF-Token', $('[name="_csrfToken"]').val());
                $(".page-loader").removeClass('hide');
            },
            success: function(data){
                $("#modal-container").html(data);
                $(".page-loader").addClass('hide');
            },
            error: function (status, error, datos){
                $(".page-loader").addClass('hide');
                Swal.fire({icon: 'error',title: '',text: 'Ha ocurrido un error, por favor intente nuevamente',footer: ''});
            }
        });
    });


    $(".btn-permisos").click(function(){
        url=$(this).data('url');
        data=$("#listado-personas").serialize();
        $.ajax({
            type: "POST",
            url: url,
            dataType: "html",
            data:data,
            beforeSend: function(xhr){
                xhr.setRequestHeader('X-CSRF-Token', $('[name="_csrfToken"]').val());
                $(".page-loader").removeClass('hide');
            },
            success: function(data){
                $("#modal-container").html(data);
                $(".page-loader").addClass('hide');
            },
            error: function (status, error, datos){
                $(".page-loader").addClass('hide');
                Swal.fire({icon: 'error',title: '',text: 'Ha ocurrido un error, por favor intente nuevamente',footer: ''});
            }
        });
    });


    $(".btn-eliminar").click(function(){
        url=$(this).data('url');

        Swal.fire({
            title: '',
            text: "¿Seguro desea eliminar esta persona?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Eliminar',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.value){
                data=$("#listado-personas").serialize();
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType: "json",
                    data:data,
                    beforeSend: function(xhr){
                        xhr.setRequestHeader('X-CSRF-Token', $('[name="_csrfToken"]').val());
                        $(".page-loader").removeClass('hide');
                    },
                    success: function(data){
                        $(".page-loader").addClass('hide');
                        if(data.result){
                            Swal.fire({icon: 'success',title: '',text: data.mensaje, footer: ''})
                            .then((result) => {
                                if(result.value){
                                    selPage=$(".page-number[tabindex='-1']");
                                    if(selPage.length === 0){
                                        $("#buscar").trigger('click');
                                    }else{
                                        selPage.trigger('click');
                                    }
                                }
                            });
                        }else{
                            Swal.fire({icon: 'error',title: '',text: data.mensaje, footer: ''});
                        }
                    },
                    error: function (status, error, datos){
                        $(".page-loader").addClass('hide');
                        Swal.fire({icon: 'error',title: '',text: 'Ha ocurrido un error, por favor intente nuevamente',footer: ''});
                    }
                });
            }
        });
    });


    $(".btn-reciclar").click(function(){
        url=$(this).data('url');

        Swal.fire({
            title: '',
            text: "¿Seguro desea reciclar esta persona?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Reciclar',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.value){
                data=$("#listado-personas").serialize();
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType: "json",
                    data:data,
                    beforeSend: function(xhr){
                        xhr.setRequestHeader('X-CSRF-Token', $('[name="_csrfToken"]').val());
                        $(".page-loader").removeClass('hide');
                    },
                    success: function(data){
                        $(".page-loader").addClass('hide');
                        if(data.result){
                            Swal.fire({icon: 'success',title: '',text: data.mensaje, footer: ''})
                            .then((result) => {
                                if(result.value){
                                    selPage=$(".page-number[tabindex='-1']");
                                    if(selPage.length === 0){
                                        $("#buscar").trigger('click');
                                    }else{
                                        selPage.trigger('click');
                                    }
                                }
                            });
                        }else{
                            Swal.fire({icon: 'error',title: '',text: data.mensaje, footer: ''});
                        }
                    },
                    error: function (status, error, datos){
                        $(".page-loader").addClass('hide');
                        Swal.fire({icon: 'error',title: '',text: 'Ha ocurrido un error, por favor intente nuevamente',footer: ''});
                    }
                });
            }
        });
    });

</script>